/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * TodosAPI
 * OpenAPI spec version: v1
 */

export interface ReadTodoDto {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  title?: string | null;
  isCompleted?: boolean;
}
